SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[tsu_error] 
	@errorNr INT 
-- GENERAL INFO:    This stored procedure is a part of the tsqlunit
--                  unit testing framework. It is open source software
--                  available at http://tsqlunit.sourceforge.net
--
-- DESCRIPTION:     This procedure can be called by a unit test when an
--                  error occurs. Normally this should not be necessary, the 
--                  runTestSuite procedure does this automatically. 
-- PARAMETERS:      @errorNr        An error number
--
-- RETURNS:         Nothing
-- 
-- VERSION:         tsqlunit-0.91
-- COPYRIGHT:
--    Copyright (C) 2002-2009  Henrik Ekelund 
--    Email: <http://sourceforge.net/sendmessage.php?touser=618411>
--
--    This library is free software; you can redistribute it and/or
--    modify it under the terms of the GNU Lesser General Public
--    License as published by the Free Software Foundation; either
--    version 2.1 of the License, or (at your option) any later version.
--
--    This library is distributed in the hope that it will be useful,
--    but WITHOUT ANY WARRANTY; without even the implied warranty of
--    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
--    Lesser General Public License for more details.
--
--    You should have received a copy of the GNU Lesser General Public
--    License along with this library; if not, write to the Free Software
--    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA 

------------------------------------------------------------------------------------
-- Modifications:
--
--	12/09/2010 JMJ: 
--	*	Change failure message variable from nvarchar(255) to NVARCHAR(max) for entire app
--	*	Changed @msg variable from nvarchar(255) to NVARCHAR(max)
--
------------------------------------------------------------------------------------
       
AS
BEGIN
	SET NOCOUNT ON
	DECLARE @msg NVARCHAR(max)

	IF @errorNr=14000 -- User defined error message generated by RAISERRROR 
		SET @msg='User defined error'
	ELSE
		-- AE, 2009-06-10, FIX: https://apps.sourceforge.net/trac/tsqlunit/ticket/3
		SET @msg=(SELECT 'Severity: ' + CAST([severity] AS VARCHAR(10)) + ' Description:' + [description] FROM master.dbo.[sysmessages] 
            WHERE [error]=@errorNr AND msglangid = SERVERPROPERTY('LCID'))			        

	UPDATE tsuActiveTest 	
		SET 
            isError=1, 
            isFailure=0,
			message=@msg
END
GO
